---
galaxy_info:
  author: dannixon
  description: Configures automatic mounting of the ISIS data archive.
  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal

dependencies: []
